name: Upload JAR - Docker Create - Push Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-push-docker-hub:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Project and Create Docker image using Gradle
        run: ./gradlew bootBuildImage
      - name: Extract Gradle Project Name
        run: echo "PROJECT_NAME_ENV_VAR=$(./gradlew properties --no-daemon --console=plain -q | grep "^name:" | awk '{printf $2}')" >> $GITHUB_ENV
      - name: Extract Gradle Project Version
        run: echo "PROJECT_VERSION_ENV_VAR=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')" >> $GITHUB_ENV
      - name: Show extracted Gradle project version
        run: echo $PROJECT_NAME_ENV_VAR:$PROJECT_VERSION_ENV_VAR
        
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-rest-gradle-JAR
          path: build/libs
          compression-level: 0 # no compression

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push ismaelgueyetraining/$PROJECT_NAME_ENV_VAR:$PROJECT_VERSION_ENV_VAR
